function addjavaclasspathlinux
javaaddpath('/home/sja/workspaces/eclipse/modelgui/TinyLine/bin')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/TinyLine/lib')

javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/bin')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/batik-awt-util.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/batik-bridge.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/batik-css.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/batik-dom.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/batik-extension.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/batik-ext.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/batik-gui-util.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/batik-gvt.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/batik-parser.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/batik-script.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/batik-svg-dom.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/batik-svggen.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/batik-swing.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/batik-transcoder.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/batik-util.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/batik-xml.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/js.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/pdf-transcoder.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/xerces_2_5_0.jar')
javaaddpath('/home/sja/workspaces/eclipse/modelgui/batik-1.6/lib/xml-apis.jar')